### ISSUE TITLE
Audio_Input_Processor error

### ISSUE THREAD

**Issue by Colin1964** [t1m0thyj/AssistantPi#11]
Setup and Installation didn't flag up any errors but when the demo runs at the end of the install I get this error. I thought the error was associated with my USB Mic set up so did a quick test using `arecord` and `aplay` and everything works fine - i.e. I can playback the file that I record. Does the fact that the error says "audio processor" and not "Device" suggest to this is system configuration and not hardware related?
`pi@raspberrypi:~/AIY-projects-python $ source env/bin/activate && env/bin/python3 -u src/AssistantPi.py
ON_MUTED_CHANGED:
  {'is_muted': False}
[2604:2626:ERROR:audio_input_processor.cc(748)] Input error
/home/pi/AIY-projects-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
ON_START_FINISHED
Say "OK, Google" then speak, or press Ctrl+C to quit...
[2604:2630:ERROR:audio_input_processor.cc(748)] Input error
`

**Comment by t1m0thyj** [comment]
Have you created a `~/.asoundrc` file with configuration for your USB mic as described [here](https://developers.google.com/assistant/sdk/guides/library/python/embed/audio)? Even if your mic and speakers seem to be working fine with `aplay` and `arecord`, I believe that Assistant requires that config file.

**Comment by Colin1964** [comment]
@t1m0thyj Many thanks for the response. Turns out I had  forgotten about another voice service I had running on my Pi that was set up to start on bootup. This was obviously conflicting with assistant service. I disabled the offending service and now it works fine. I also noted one other thing that you may want to add to your "excellent" guide too. The default volume level of the assistant is very low. I had used Aplay to test the speaker and volume levels I turned my speaker down to what seemed a reasonable volume level. However when I then used assistant with the speakers set at this volume the assistant response was only just audible. Turning the speaker volume to max (and setting max volume on alsamixer) still resulted in low volume levels from the assistant. The solution couldn't be more simple. Just tell the assistant "Hey Google, set volume to maximum" and hey presto assistant is now loud and clear.
