### ISSUE TITLE
Error on Pi Zero

### ISSUE THREAD

**Issue by Elijah067** [t1m0thyj/AssistantPi#12]
I am using raspberry pi zero w and installed raspbian via noobs. 

I run the bash install.sh and got an error of "Cannot run hotword demo on Pi zero!"

**Comment by t1m0thyj** [comment]
The official Assistant package only works on Pi 2's and 3's which have an ARM7 CPU. The Zero W has an ARM6 CPU, so the hotword detection ("OK Google" functionality) won't work on it. I would suggest trying [this repository](https://github.com/warchildmd/google-assistant-hotword-raspi) instead, an alternative version someone made that should work on Pi Zeros. I'll also add a warning to the README that this repository will only work for ARM7 devices.
