### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Gfermoto** [t1m0thyj/AssistantPi#15]
google-api-core 0.1.4 has requirement requests<3.0.0dev,>=2.18.0, but you'll hav               e requests 2.14.2 which is incompatible.
pyasn1-modules 0.2.2 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn               1 0.1.9 which is incompatible.

**Comment by t1m0thyj** [comment]
I know the install process shows several messages similar to that which look like errors, but they come from pip (the Python package manager) and I don't really have control over them. If these are the only error messages and you can run Assistant after the install script finishes you should be good. If not feel free to reopen this issue.
