### ISSUE TITLE
Installation failed import error

### ISSUE THREAD

**Issue by parismorton** [t1m0thyj/AssistantPi#2]
Hi, the installation was running until it halted at ImportError: No module named 'google_auth_oauthlib'. I tried what you said in the other issue thread to go into AIY-projects-python and install google_auth_oauthlib there, but the install still ends up at no module named.

**Comment by t1m0thyj** [comment]
I just pushed a fix for this that I tested on my Pi. Run a `git pull` in the AssistantPi folder on your Pi to get the fix, then `uninstall.sh` to remove the old installation from your Pi, then `install.sh` to run the latest install script containing the fix.

**Comment by alexsgocart** [comment]
I was having the same issue as parismorton.

I did exactly what you said and it is working now. Thanks!

**Comment by t1m0thyj** [comment]
e784d4c adds a temporary workaround, if Google accepts [this PR](https://github.com/google/aiyprojects-raspbian/pull/469) that would be the ideal fix.
